# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'HeadViewController' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for HeadViewController

  target 'HeadViewControllerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HeadViewControllerUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'AFNetworking'
pod 'YYWebImage'
end
